name: Builds
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build macos-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      # Set up Flutter.      
      # - name: Install OpenJDK
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: '11'
      - name: Get latest stable version of Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - run: flutter --version
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get -v
      - run: flutter test
      - run: flutter build web
      - run: flutter build ios --release --no-codesign
      # - run: flutter build apk
      # - run: flutter build appbundle      